# Generated by Django 3.2.23 on 2023-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_key',
            field=models.CharField(default=12.0, max_length=100),
            preserve_default=False,
        ),
    ]
